services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-yovi_db}
    ports:
      - "3306:3306"
    volumes:
      - ./users/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - monitor-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  users:
    build: ./users
    container_name: users
    image: ghcr.io/arquisoft/yovi_es5a-users:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST:-mysql}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-rootpassword}
      DB_NAME: ${DB_NAME:-yovi_db}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - monitor-net

  webapp:
    build:
      context: ./webapp
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: webapp
    image: ghcr.io/arquisoft/yovi_es5a-webapp:latest
    ports:
      - "80:80"
    depends_on:
      - users
    networks:
      - monitor-net

  gamey:
    build: ./gamey
    container_name: gamey
    image: ghcr.io/arquisoft/yovi_es5a-gamey:latest
    ports:
      - "4000:4000"
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./users/monitoring/prometheus:/etc/prometheus
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - ./users/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
  mysql_data:
